### ISSUE TITLE
Open source checklist

### ISSUE THREAD

**Issue by fleischp** [compas-rrc/compas_rrc#8]
- [x] Add continuous integration to build RRC in Github Actions
- [x] Add rrc to Zenodo to have a citable DOI
- [x] Add pip/conda badges
- [x] Reword the `Installation` section
- [x] Check if compas_rrc_start repo is already published otherwise remove from `README.rst`.
- [x] Add link to documentation website on Github repo
- [x] New docker image needed?

**Comment by gonzalocasas** [comment]
It's done!
